// CARET MODIFICATION: Converted from CommonJS to ES6 modules for Vite compatibility
// Original backed up to: grpc-client-js.cline
// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js
import { createGrpcClient } from "./grpc-client-base.js"
import { AccountServiceDefinition } from "@shared/proto/account"
import { BrowserServiceDefinition } from "@shared/proto/browser"
import { CheckpointsServiceDefinition } from "@shared/proto/checkpoints"
import { FileServiceDefinition } from "@shared/proto/file"
import { McpServiceDefinition } from "@shared/proto/mcp"
import { StateServiceDefinition } from "@shared/proto/state"
import { TaskServiceDefinition } from "@shared/proto/task"
import { WebServiceDefinition } from "@shared/proto/web"
import { ModelsServiceDefinition } from "@shared/proto/models"
import { SlashServiceDefinition } from "@shared/proto/slash"
import { UiServiceDefinition } from "@shared/proto/ui"

export const AccountServiceClient = createGrpcClient(AccountServiceDefinition)
export const BrowserServiceClient = createGrpcClient(BrowserServiceDefinition)
export const CheckpointsServiceClient = createGrpcClient(CheckpointsServiceDefinition)
export const FileServiceClient = createGrpcClient(FileServiceDefinition)
export const McpServiceClient = createGrpcClient(McpServiceDefinition)
export const StateServiceClient = createGrpcClient(StateServiceDefinition)
export const TaskServiceClient = createGrpcClient(TaskServiceDefinition)
export const WebServiceClient = createGrpcClient(WebServiceDefinition)
export const ModelsServiceClient = createGrpcClient(ModelsServiceDefinition)
export const SlashServiceClient = createGrpcClient(SlashServiceDefinition)
export const UiServiceClient = createGrpcClient(UiServiceDefinition)
